rplugin/python3/defx/defx.py

According [this][1], we can use tuple comparison to improve `version_check()` readability.
For example,  (3,6,0) < (3,6,1)
[1]: https://stackoverflow.com/questions/5292303/how-does-tuple-comparison-work-in-python

Improve version check readability by not using too more if_else

---

doc/defx.txt
rplugin/python3/defx/action.py
rplugin/python3/defx/util.py

Hi,
This PR contains two things:
1. Creating parent directories of a new file name.
This allows providing file name like `myfolder/newfolder/newfile.py`, and action will take care of creating any parent folders, in this case `myfolder/newfolder`, if they doesn't exist.
2. Removing files/directories.
I added confirm to make sure someone didn't press remove action accidentally. I know you planned to add this, but i wanted to help, and this is something that i'm really missing at this moment.

Create parent directories from new file name if provided and add remove action

---

rplugin/python3/defx/view.py

Wrapping really messes up layout, so it must be disabled.
Also, there's no reason to list defx buffer in the buffers list, it can be opened with command at any time.

Do not wrap text in defx and do not list it in buffers.

---

autoload/defx/util.vim

Fix a problem that path completion doesn't work when argument has "~/" or "../" on both Ubuntu 16.04 and Windows 10.

Fix path completion on command mode

---

rplugin/python3/defx/column/mark.py

I want to use some double-bytes icons for marks from [Nerd Fonts][], for example.  But in the latest master, marks are considered to have one char.
[Nerd Fonts]: https://nerdfonts.com
So when set to this,
```vim
call defx#custom#column('mark', {
\ 'directory_icon': nr2char(0xe5ff),
\ 'readonly_icon': nr2char(0xe0a2),
\ 'root_icon': nr2char(0xe5fe),
\ 'selected_icon': '✓',
\ })
```
It seems tight a bit.
This patch enables to set length for marks and solve this.
```vim
call defx#custom#column('mark', {
\ 'directory_icon': nr2char(0xe5ff) . ' ',
\ 'readonly_icon': nr2char(0xe0a2) . ' ',
\ 'root_icon': nr2char(0xe5fe) . ' ',
\ 'selected_icon': '✓ ',
\ 'length': 2,
\ })
```

Enable to custom length of marks

---

rplugin/python3/defx/defx.py

When working inside a project that is inside a sym link, and then opening defx and then opening another file in this project, defx will resolve all the sym links in the path.  It is better to use the same path (with the sym links)

Changed to not resolve symbolic links in the given directory path

---

rplugin/python3/defx/base/kind.py
rplugin/python3/defx/kind/file.py

ref #117 
I think using the decorator to register an action is more flexible than manually registering the action. Just like:
```py
@action(name='cd')
def _cd(view: View, defx: Defx, context: Context) -> None:
```
I'm not sure if there is compatibility with such a change, I just did some manual testing.

[WIP] Improve action register mechanism

---

rplugin/python3/defx/view.py

1. nvim -u init.vim
init.vim
```viml
set rtp+=~/test_nvim/defx.nvim/
```
1. `:Defx`
1. `:bd`
1. `:Defx -resume`
If defx buffer is in unlisted state, -resume cannot restore buffer.

use buflisted instead

---

rplugin/python3/defx/kind/file.py

This pr will fix `drop` action problem.
`bufnr()` requires a file pattern if you want to match exactly.
1. open `.env.sample`
2. `Defx -split=vertical`
3. execute drop action `.env`
4. but move to `.env.sample` window
- https://vim-jp.org/vimdoc-ja/eval.html#bufname()

Fix drop action

---

rplugin/python3/defx/util.py

In this situation:
```
Please input a new filename: test.py |
```
(here `|` is the cursor)
And then defx will creates a file `test.py ` but not `test.py`. So the input must be trimmed firstly

Remove whitespaces in filename and dirname

---

rplugin/python3/defx/rplugin.py
rplugin/python3/defx/view.py

Redraw function should not limit the current defx buffer.

allow View.redraw() redraw defx buffer when not current buffer, avoid window jump

---

rplugin/python3/defx/view.py

* defx version(SHA1): e4259b3
* OS: macos
* neovim/Vim version: NVIM v0.4.0-1856-g82d52b229
min_vimrc.vim
```vim
set rtp+=~/test_vim/defx.nvim/
nnoremap <silent> <Space>e :<C-u>Defx -split=vertical -direction=topleft -winwidth=40 -listed -resume <CR>
let $NVIM_RPLUGIN_MANIFEST = './defx_rplugin.vim'
autocmd filetype defx call Defx_ft()
func Defx_ft()
nnoremap <silent><buffer><expr> o defx#async_action('open_or_close_tree')
nnoremap <silent><buffer><expr> l defx#async_action('open')
endf
```
1. prepare files
```bash
mkdir fool
mkdir fool/dir_{1..1000}
touch fool/dir_{1..1000}/document.txt
```
2. nvim -u min_vimrc.vim
3. `<space>e` open defx and `l` go to `fool` dir
4. `G` to `dir_1000/`, and use `o` to open
5. use `o` again for close, you will see cursor jump to line and then jump back to …

fix cursor jump

---

rplugin/python3/defx/kind/file.py

This always tries to set the path of the opened file relative to the current working directory, fixing #202.

Use relative path when opening file with open or drop

---

rplugin/python3/defx/kind/file.py

After pasted, moved files doesn't exist any more, clipboard should be cleared, otherwise future pasting will panic.
No panic in future pasting.
```vim
set nocompatible
set runtimepath+=~/.cache/vim/dein/repos/github.com/Shougo/defx.nvim
augroup defx_init
autocmd FileType defx call s:defx_init()
augroup END
function! s:defx_init() abort
nnoremap <silent><buffer><expr> o             defx#do_action('open_tree', ['nested'])
nnoremap <silent><buffer><expr> m             defx#do_action('move')
nnoremap <silent><buffer><expr> p             defx#do_action('paste')
nnoremap <silent><buffer><expr> <Space>       defx#async_action('toggle_select') . 'j'
endfunction
exe 'helptags ALL'
```

Clear clipboard after moved

---

rplugin/python3/defx/kind/file.py

The fix for issue #238 removed support for opening files using relative paths in the `drop` command. While this fixes the issue at hand, it also removes useful functionality (see i.e. #202 and #203 where I fixed the broken behaviour).
Checking parameters for `getcwd()` I noticed it is possible to ignore window local working directories as set by `:lcd`, only reading the tab's directory. Adapting the restored code for applying relative paths, this fixes the issue for @Freed-Wu and still retains the old functionality.
To test, the same scenario can be used as described in #238. Tested on NVIM v0.5.0-dev.

Restore relative paths for `drop` command

---

rplugin/python3/defx/sort.py

I want to sort files by filename among same extension files.
This PR enable to specify second or more sort key (e.g. `-sort=extension:filename`)

Enable sort by multiple keys

---

rplugin/python3/defx/kind/file.py

Enable action `new_multiple_files` create one directory `1 3` and two files: `123`, `12 3` with parameters:`1\ 3/ 123 '12 3'`.

Enable new_multiple_files action support escaped space and quotes.

---

doc/defx.txt
rplugin/python3/defx/column/filename.py

Hello Shougo,
Please consider this. It allows column to have dynamic width depending on width of
other columns and total buffer width. This makes column to always fit fully available space.
It allows right alignment of columns right to column using this negative max_width.
Looks much nicer than current percentage where the column width is always a bit off because it is percentage.

Treat negative max_width column as absolute value, not as percentage

---

autoload/defx/init.vim
autoload/defx/util.vim
rplugin/python3/defx/kind/file.py
rplugin/python3/defx/view.py

By this PR, previewing other images and closing defx closes existing previewed image.
I used vim script for controlling job to handle Vim's job object.

 Improve previewing image behavior.

---

rplugin/python3/defx/clipboard.py
rplugin/python3/defx/kind/file.py

This PR allows external sources to send files to local path.
Sending files will become possible by defining `Clipboard.paster`, which tells how to send external files to local.
This is an example using this feature: copy action of my [sftp source](https://github.com/matsui54/defx-sftp).
``` python
@action(name='copy')
def _copy(view: View, defx: Defx, context: Context) -> None:
if not context.targets:
return
message = 'Copy to the clipboard: {}'.format(
str(context.targets[0]['action__path'])
if len(context.targets) == 1
else str(len(context.targets)) + ' files')
view.print_msg(message)
def copy_to_local(path: str, dest: str):
client = defx._source.client
client.get(path, dest)
view._clipboard.action = ClipboardAction.COPY
view._clipboard.candidates = context.targets …
```

Allow external sources to copy files to local

---

rplugin/python3/defx/base/kind.py
rplugin/python3/defx/kind/file.py
rplugin/python3/defx/kind/filelike.py

When creating sources and kinds in `defx/kind/*.py`, I must write a lot of code which is the same as `defx/kind/file.py`.
For example, [here](https://github.com/matsui54/defx-sftp/blob/b58059f687d9f5d9e13b10ed43e9925ddeae6b27/rplugin/python3/defx/kind/sftp.py) is the definition of actions in [defx-sftp](https://github.com/matsui54/defx-sftp).
Though most of the code is the same as `kind/file.py`, some actions must be redefined for `SFTPPath`.
This duplication of code makes it difficult to maintain external sources.
User-defined kinds can be written in the following way.
- Users send objects which has the same methods as `pathlib.Path` like `is_dir()` or `mkdir()` as candidates in `get_root_candidate()` and `get_root_candidate()` in `source/*.py`
This can be done like [this …

[RDY] Make creating sources easier

---

rplugin/python3/defx/view.py

When quitting defx after previewing files and then deleting it, defx tries to delete non-existing buffer, throwing error: `E516: No buffers were deleted`

Don't delete removed files buffer
